// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: ai-service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { HealthReq, HealthResp } from "./common";

export const protobufPackage = "tagmi.ai.service";

/** Message placeholders */
export interface Empty {
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty = {
  encode(_: Empty, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Empty {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

/** Basic health service and placeholders for gRPC methods */
export type ai_serviceServiceService = typeof ai_serviceServiceService;
export const ai_serviceServiceService = {
  health: {
    path: "/tagmi.ai.service.ai_serviceService/Health",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: HealthReq) => Buffer.from(HealthReq.encode(value).finish()),
    requestDeserialize: (value: Buffer) => HealthReq.decode(value),
    responseSerialize: (value: HealthResp) => Buffer.from(HealthResp.encode(value).finish()),
    responseDeserialize: (value: Buffer) => HealthResp.decode(value),
  },
} as const;

export interface ai_serviceServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthReq, HealthResp>;
}

export interface ai_serviceServiceClient extends Client {
  health(request: HealthReq, callback: (error: ServiceError | null, response: HealthResp) => void): ClientUnaryCall;
  health(
    request: HealthReq,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HealthResp) => void,
  ): ClientUnaryCall;
  health(
    request: HealthReq,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HealthResp) => void,
  ): ClientUnaryCall;
}

export const ai_serviceServiceClient = makeGenericClientConstructor(
  ai_serviceServiceService,
  "tagmi.ai.service.ai_serviceService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ai_serviceServiceClient;
  service: typeof ai_serviceServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };
